### ISSUE TITLE
Move a Github Wiki?

### ISSUE THREAD

**Issue by JamesNewton** [xiatechs/markdown-to-confluence#31]
Github wiki's can be exported as a git repo and stored locally in the file system. I'm hoping we can use this code to move those wiki pages to Confluence. But there is a comment in your documentation about markup being in the same folder as the code which makes me wonder if it would work for that. Is code expected or required? Or will it work with only markup text?

**Comment by tbal999** [comment]
Hey @JamesNewton it'll work without the code.

I'll update the guide so it's clearer.
