### ISSUE TITLE
Can't figure out puml image generation

### ISSUE THREAD

**Issue by littlebeeper** [xiatechs/markdown-to-confluence#32]
Hi,

Thanks a lot for this nice tool. It's exactly what we need.
However, we can't seem to figure out how to generate images from puml.
We managed to get it working only by copying [the node folder](https://github.com/xiatechs/markdown-to-confluence/tree/master/node) to our repo. 

Could you please let us know if there is a certain pattern involved?

Thanks

**Comment by tbal999** [comment]
Hi @littlebeeper sure, glad you like it.

that's an interesting way to use the tool - the way it's intended to be used is as a github action via a configuration like below:

`name: MTC
on:
  push:
    branches:
      - master

jobs:
  markdown:
    name: Markdown To Confluence Action
    runs-on: ubuntu-latest
    steps:
      - name: gather branch details
        shell: bash
        run: |
             if [ -z "${GITHUB_HEAD_REF}" ]
             then
              echo NOT pull request, branch = $(echo ${GITHUB_REF#refs/heads/})
              echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
             else
              echo pull request, branch = $(echo ${GITHUB_HEAD_REF})
              echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
             fi
        id: extract_branch          

      - name: checkout markdown action
        uses: actions/checkout@v2-beta
        with:
          repository: xiatechs/markdown-to-confluence
          ref: refs/tags/v1.23
      - name: checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
          path: './example-repo'
          fetch-depth: 0
      - name: run markdown to confluence action
        uses: ./
        with:
          key: ${{ secrets.CONFLUENCE_KEY }}
          space: "EXAMPLE"
          username: ${{ secrets.CONFLUENCE_USERNAME }}
          repo: './example-repo'
          url: "https://yourcompany.atlassian.net/"`

**Comment by tbal999** [comment]
to answer your question:

- you need to download an additional application - plantuml.jar which this tool calls during it's running to convert go code into .puml files - before it then created images for each folder that contains go code:

```
RUN apk add --no-cache graphviz ttf-droid ttf-droid-nonlatin curl \
    && apk add --no-cache \
        --repository https://nl.alpinelinux.org/alpine/edge/testing \
    && mkdir /app \
    && curl -L https://sourceforge.net/projects/plantuml/files/plantuml.${PLANTUML_VERSION}.jar/download -o /app/plantuml.jar \
    && apk del curl
```

**Comment by tbal999** [comment]
you _may_ need to run this first: **apk add openjdk11**

**Comment by littlebeeper** [comment]
Hi,

Thanks a lot for your reply and help.
We thought initially that the tool was actually generating an png image from the [puml file](https://github.com/xiatechs/markdown-to-confluence/blob/master/markdown/markdown-markdown-to-confluence-pumldiagram.puml) that was committed.
 
We figured out later that the tool actually generates a puml file dynamically from the **go** package/module then converts it to a png diagram.
It looks like that puml file has no effect and most likely committed by mistake.

**Comment by tbal999** [comment]
Yeah i agree with that. 
Does this feel resolved to you?

**Comment by littlebeeper** [comment]
Yes! 👍
